algoritmo "triangulo"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Elberth Lins Costa de Moraes
// Função : Calcular Área
// Autor : Renata Duarte
// Data : 03/02/2022
// Seção de Declarações 
var
    base,altura : real

inicio
      escreva ("Qual a base do triângulo? ")
      leia (base)
      escreva ("Qual a altura do triângulo? ")
      leia (altura)
      escreva ("A área do triângulo é", (base*altura)/2)
      
fimalgoritmo
